// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

namespace Template.Web.Areas.Admin.Users
{
    public partial class UsersController
    {
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public UsersController()
        {
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected UsersController(Dummy d)
        {
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<IActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<IActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPage(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPage(Task<IActionResult> taskResult)
        {
            return RedirectToPage(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPagePermanent(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPagePermanent(Task<IActionResult> taskResult)
        {
            return RedirectToPagePermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult Index()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult ShowDevice()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.ShowDevice);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult EditDevice()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditDevice);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DeleteDevice()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteDevice);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DetailsUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DetailsUser);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult EditUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DeleteUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public UsersController Actions => MVC.Admin.Users;
        [GeneratedCode("R4Mvc", "1.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("R4Mvc", "1.0")]
        public readonly string Name = "Users";
        [GeneratedCode("R4Mvc", "1.0")]
        public const string NameConst = "Users";
        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionNamesClass s_ActionNames = new ActionNamesClass();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames => s_ActionNames;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreateDevice = "CreateDevice";
            public readonly string ShowDevice = "ShowDevice";
            public readonly string EditDevice = "EditDevice";
            public readonly string DeleteDevice = "DeleteDevice";
            public readonly string IndexUsers = "IndexUsers";
            public readonly string DetailsUser = "DetailsUser";
            public readonly string CreateUser = "CreateUser";
            public readonly string EditUser = "EditUser";
            public readonly string DeleteUser = "DeleteUser";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreateDevice = "CreateDevice";
            public const string ShowDevice = "ShowDevice";
            public const string EditDevice = "EditDevice";
            public const string DeleteDevice = "DeleteDevice";
            public const string IndexUsers = "IndexUsers";
            public const string DetailsUser = "DetailsUser";
            public const string CreateUser = "CreateUser";
            public const string EditUser = "EditUser";
            public const string DeleteUser = "DeleteUser";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_Index s_IndexParams = new ActionParamsClass_Index();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams => s_IndexParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string page = "page";
            public readonly string searchTerm = "searchTerm";
            public readonly string deviceTypeFilter = "deviceTypeFilter";
            public readonly string deviceStatusFilter = "deviceStatusFilter";
            public readonly string deviceWarrantyFilter = "deviceWarrantyFilter";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_Index s_IndexParams = new ActionParamsClass_Index();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams => s_IndexParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_CreateDevice s_CreateDeviceParams = new ActionParamsClass_CreateDevice();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateDevice CreateDeviceParams => s_CreateDeviceParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateDevice
        {
            public readonly string indexViewModel = "indexViewModel";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_ShowDevice s_ShowDeviceParams = new ActionParamsClass_ShowDevice();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowDevice ShowDeviceParams => s_ShowDeviceParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowDevice
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_EditDevice s_EditDeviceParams = new ActionParamsClass_EditDevice();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDevice EditDeviceParams => s_EditDeviceParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDevice
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_EditDevice s_EditDeviceParams = new ActionParamsClass_EditDevice();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDevice EditDeviceParams => s_EditDeviceParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDevice
        {
            public readonly string indexViewModel = "indexViewModel";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DeleteDevice s_DeleteDeviceParams = new ActionParamsClass_DeleteDevice();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDevice DeleteDeviceParams => s_DeleteDeviceParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDevice
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DetailsUser s_DetailsUserParams = new ActionParamsClass_DetailsUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsUser DetailsUserParams => s_DetailsUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_EditUser s_EditUserParams = new ActionParamsClass_EditUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUser EditUserParams => s_EditUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DeleteUser s_DeleteUserParams = new ActionParamsClass_DeleteUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams => s_DeleteUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames => s_ViewNames;
            public class _ViewNamesClass
            {
            }
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ViewsClass s_Views = new ViewsClass();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ViewsClass Views => s_Views;
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_UsersController : Template.Web.Areas.Admin.Users.UsersController
    {
        public R4MVC_UsersController(): base(Dummy.Instance)
        {
        }

        [NonAction]
        partial void IndexOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int page, string searchTerm, string deviceTypeFilter, string deviceStatusFilter, string deviceWarrantyFilter);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult Index(int page, string searchTerm, string deviceTypeFilter, string deviceStatusFilter, string deviceWarrantyFilter)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceTypeFilter", deviceTypeFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceStatusFilter", deviceStatusFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceWarrantyFilter", deviceWarrantyFilter);
            IndexOverride(callInfo, page, searchTerm, deviceTypeFilter, deviceStatusFilter, deviceWarrantyFilter);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, Template.Web.Areas.Admin.Users.IndexViewModel model);
        [NonAction]
        public override System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> Index(Template.Web.Areas.Admin.Users.IndexViewModel model)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult<Microsoft.AspNetCore.Mvc.IActionResult>(callInfo);
        }

        [NonAction]
        partial void CreateDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult CreateDevice()
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.CreateDevice);
            CreateDeviceOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, Template.Web.Areas.Admin.Users.IndexViewModel indexViewModel);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult CreateDevice(Template.Web.Areas.Admin.Users.IndexViewModel indexViewModel)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.CreateDevice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "indexViewModel", indexViewModel);
            CreateDeviceOverride(callInfo, indexViewModel);
            return callInfo;
        }

        [NonAction]
        partial void ShowDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult ShowDevice(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.ShowDevice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShowDeviceOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult EditDevice(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditDevice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditDeviceOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, Template.Web.Areas.Admin.Users.IndexViewModel indexViewModel);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult EditDevice(Template.Web.Areas.Admin.Users.IndexViewModel indexViewModel)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditDevice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "indexViewModel", indexViewModel);
            EditDeviceOverride(callInfo, indexViewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDeviceOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DeleteDevice(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteDevice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteDeviceOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void IndexUsersOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult IndexUsers()
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.IndexUsers);
            IndexUsersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DetailsUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DetailsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult CreateUser()
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            CreateUserOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EditUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult EditUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DeleteUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteUserOverride(callInfo, id);
            return callInfo;
        }
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
