// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

namespace Template.Web.Areas.Admin_Full.Users
{
    public partial class UsersController
    {
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public UsersController()
        {
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected UsersController(Dummy d)
        {
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<IActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<IActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPage(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPage(Task<IActionResult> taskResult)
        {
            return RedirectToPage(taskResult.Result);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPagePermanent(IActionResult result)
        {
            var callInfo = result.GetR4ActionResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToPagePermanent(Task<IActionResult> taskResult)
        {
            return RedirectToPagePermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult Index()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DetailsUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DetailsUser);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult EditUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DeleteUser()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
        }

        [NonAction]
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public virtual IActionResult DeleteConfirmed()
        {
            return new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public UsersController Actions => MVC.Admin_Full.Users;
        [GeneratedCode("R4Mvc", "1.0")]
        public readonly string Area = "Admin_Full";
        [GeneratedCode("R4Mvc", "1.0")]
        public readonly string Name = "Users";
        [GeneratedCode("R4Mvc", "1.0")]
        public const string NameConst = "Users";
        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionNamesClass s_ActionNames = new ActionNamesClass();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames => s_ActionNames;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string DetailsUser = "DetailsUser";
            public readonly string CreateUser = "CreateUser";
            public readonly string EditUser = "EditUser";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string DeleteConfirmed = "DeleteConfirmed";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string DetailsUser = "DetailsUser";
            public const string CreateUser = "CreateUser";
            public const string EditUser = "EditUser";
            public const string DeleteUser = "DeleteUser";
            public const string DeleteConfirmed = "DeleteConfirmed";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_Index s_IndexParams = new ActionParamsClass_Index();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams => s_IndexParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string page = "page";
            public readonly string searchTerm = "searchTerm";
            public readonly string deviceTypeFilter = "deviceTypeFilter";
            public readonly string deviceStatusFilter = "deviceStatusFilter";
            public readonly string deviceWarrantyFilter = "deviceWarrantyFilter";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DetailsUser s_DetailsUserParams = new ActionParamsClass_DetailsUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailsUser DetailsUserParams => s_DetailsUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailsUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_CreateUser s_CreateUserParams = new ActionParamsClass_CreateUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateUser CreateUserParams => s_CreateUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateUser
        {
            public readonly string userViewModel = "userViewModel";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_EditUser s_EditUserParams = new ActionParamsClass_EditUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUser EditUserParams => s_EditUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_EditUser s_EditUserParams = new ActionParamsClass_EditUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUser EditUserParams => s_EditUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUser
        {
            public readonly string id = "id";
            public readonly string userViewModel = "userViewModel";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DeleteUser s_DeleteUserParams = new ActionParamsClass_DeleteUser();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams => s_DeleteUserParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ActionParamsClass_DeleteConfirmed s_DeleteConfirmedParams = new ActionParamsClass_DeleteConfirmed();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteConfirmed DeleteConfirmedParams => s_DeleteConfirmedParams;
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteConfirmed
        {
            public readonly string id = "id";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames => s_ViewNames;
            public class _ViewNamesClass
            {
            }
        }

        [GeneratedCode("R4Mvc", "1.0")]
        static readonly ViewsClass s_Views = new ViewsClass();
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public ViewsClass Views => s_Views;
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_UsersController : Template.Web.Areas.Admin_Full.Users.UsersController
    {
        public R4MVC_UsersController(): base(Dummy.Instance)
        {
        }

        [NonAction]
        partial void IndexOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int page, string searchTerm, string deviceTypeFilter, string deviceStatusFilter, string deviceWarrantyFilter);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult Index(int page, string searchTerm, string deviceTypeFilter, string deviceStatusFilter, string deviceWarrantyFilter)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchTerm", searchTerm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceTypeFilter", deviceTypeFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceStatusFilter", deviceStatusFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deviceWarrantyFilter", deviceWarrantyFilter);
            IndexOverride(callInfo, page, searchTerm, deviceTypeFilter, deviceStatusFilter, deviceWarrantyFilter);
            return callInfo;
        }

        [NonAction]
        partial void DetailsUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DetailsUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DetailsUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailsUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult CreateUser()
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            CreateUserOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, Template.Web.Areas.Admin.Users.IndexViewModel userViewModel);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult CreateUser(Template.Web.Areas.Admin.Users.IndexViewModel userViewModel)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.CreateUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userViewModel", userViewModel);
            CreateUserOverride(callInfo, userViewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult EditUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id, Template.Web.Areas.Admin.Users.IndexViewModel userViewModel);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult EditUser(int id, Template.Web.Areas.Admin.Users.IndexViewModel userViewModel)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userViewModel", userViewModel);
            EditUserOverride(callInfo, id, userViewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DeleteUser(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteUserOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteConfirmedOverride(R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult callInfo, int id);
        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult DeleteConfirmed(int id)
        {
            var callInfo = new R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(Area, Name, ActionNames.DeleteConfirmed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteConfirmedOverride(callInfo, id);
            return callInfo;
        }
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
